version: '3'
services:
  database:
    image: mongo:3.4-jessie
    ports:
      - 27017:27017
    volumes:
      - ./data/:/data/db
    restart: always

  tor:
    image: dperson/torproxy:latest
    ports:
      - 9050:9050

  verge-price-tinker:
    build: .
    links:
      - database
    depends_on:
      - database
      - tor
    ports:
      - 3003:3003
    environment:
      - VPT_MONGODB_URL=${VPT_MONGODB_URL}
      - CRYPTO_COMPARE_API_KEY=${CRYPTO_COMPARE_API_KEY}
      - TOR_HOST=tor
      - TOR_PORT=9050
    restart: always
    command: yarn prod
